site_name: Optimo
nav:
    - Home: index.md
    - სახლი: test.md

theme:
  language: ka
  name: material
      
extra:
  version:
    provider: mike

plugins:
    - search
    - pdf-export:
        combined: true